name: mestre_dos_magos
description: "A new way to manage your DnD campaigns"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  parse_server_sdk_flutter: ^8.0.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.1
  get_it: ^7.6.7
  responsive_framework: ^0.1.9
  badges: ^3.1.2
  device_preview: ^1.1.0
  fluttertoast: ^8.2.5
  awesome_dialog: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: false
  image_path: "images/logo/app_icon_mago.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logo/
    - images/classes/
    - images/races/
    - images/monsters/
